Repository Diegocaceres97/lolNaliticss, pull requests merged in 2023-04, with the labels that each got.

#5 CHANGES: Creation button reset enemies in component selectChamps
  src/shared/components/selects/selectChamps.tsx
Labels: feature

#7 Feature/hu 3
  src/App.tsx
  src/shared/components/alerts/alert.ts
  src/shared/components/selects/selectChamps.tsx
Labels: HU

#8 Update dev with master
  src/App.tsx
  src/shared/components/alerts/alert.ts
  src/shared/components/selects/selectChamps.tsx
Labels: update

#9 UPDATE: eslint and prettier rules in the project
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/shared/components/enemyList.tsx
  src/shared/components/selects/selectChamps.tsx
Labels: documentation, Improvement

#12 Feature/hu 11: merge with dev
  .env.example
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/models/interfaces/champs.interface.tsx
  src/models/openAI/chatGPT.tsx
  src/shared/components/alerts/alert.ts
  src/shared/components/buttons/button.tsx
  src/shared/components/selects/selectChamps.tsx
  src/shared/contexts/contextChamps.tsx
Labels: HU, investigation

#16 changes: button changes: spinning while charging the api request🦔
  src/App.tsx
  src/models/openAI/chatGPT.tsx
  src/shared/components/alerts/alert.ts
  src/shared/components/buttons/button.tsx
  src/shared/components/selects/selectChamps.tsx
Labels: Improvement

#17 update: merge master with dev
  src/App.tsx
  src/models/openAI/chatGPT.tsx
  src/shared/components/alerts/alert.ts
  src/shared/components/buttons/button.tsx
  src/shared/components/selects/selectChamps.tsx
Labels: merge

#19 Hotfix/bug 18: done✅
  index.html
  src/shared/components/buttons/button.tsx
Labels: bug

#21 i18 Added, HU: 20 ✅
  package-lock.json
  package.json
  src/App.tsx
  src/i18.tsx
  src/lang/en.json
  src/lang/es.json
  src/main.tsx
  src/models/openAI/chatGPT.tsx
  src/shared/components/buttons/button.tsx
  src/shared/components/enemyList.tsx
  src/shared/components/selects/selectChamps.tsx
Labels: HU, Improvement

#24 HU: 23✅
  src/App.tsx
  src/lang/en.json
  src/lang/es.json
  src/shared/components/footer/footer.css
  src/shared/components/footer/footer.tsx
Labels: Improvement

#25 update main with dev: prod🚀
  src/App.tsx
  src/lang/en.json
  src/lang/es.json
  src/shared/components/footer/footer.css
  src/shared/components/footer/footer.tsx
Labels: merge, prod
